-- MySQL DDL Schema untuk Aplikasi MDTA
-- Database: mdta_db

CREATE DATABASE IF NOT EXISTS mdta_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mdta_db;

-- 1. Tabel Users (Ustadz/Pengelola)
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'USTADZ',
  `mdtaName` VARCHAR(100) NOT NULL DEFAULT 'MDTA Al-Hikmah',
  `photoUrl` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Tabel Santri
CREATE TABLE IF NOT EXISTS `santri` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `birthPlace` VARCHAR(100) NOT NULL,
  `birthDate` DATE NOT NULL,
  `gender` ENUM('LAKIKLAKI', 'PEREMPUAN') NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Tabel Presensi (Attendances)
CREATE TABLE IF NOT EXISTS `attendances` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `santriId` INT NOT NULL,
  `date` DATE NOT NULL,
  `status` ENUM('HADIR', 'SAKIT', 'IZIN', 'ALPA') NOT NULL,
  `notes` VARCHAR(255) NULL,
  `commitStatus` ENUM('DRAFT', 'FINAL') NOT NULL DEFAULT 'DRAFT',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_attendance_santri` FOREIGN KEY (`santriId`) REFERENCES `santri` (`id`) ON DELETE CASCADE,
  UNIQUE KEY `unique_santri_date` (`santriId`, `date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Tabel Pengaturan Tagihan Biaya (Fee Categories)
CREATE TABLE IF NOT EXISTS `fee_categories` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `amount` DECIMAL(12, 2) NOT NULL,
  `description` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Tabel Transaksi Pemasukan (Payments)
CREATE TABLE IF NOT EXISTS `payments` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `santriId` INT NOT NULL,
  `feeCategoryId` INT NOT NULL,
  `amount` DECIMAL(12, 2) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `notes` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_payment_santri` FOREIGN KEY (`santriId`) REFERENCES `santri` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_payment_fee` FOREIGN KEY (`feeCategoryId`) REFERENCES `fee_categories` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Tabel Setor Kas Uang di Tangan (Cash Handouts)
CREATE TABLE IF NOT EXISTS `cash_handouts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `amount` DECIMAL(12, 2) NOT NULL,
  `depositDate` DATE NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `ustadzId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_cash_ustadz` FOREIGN KEY (`ustadzId`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
